apiVersion: v1
kind: Service
metadata:
  name: smartguard-service
spec:
  selector:
    app: smartguard
  ports:
    - name: http
      port: 8000
      targetPort: 8000
    - name: streamlit
      port: 8501
      targetPort: 8501
  type: ClusterIP
